package net.alienminds.ethnogram.ui.theme

import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val lightScheme = lightColorScheme(
    primary = AppColor.green700,
    onPrimary = AppColor.white,
    primaryContainer = AppColor.green200,
    onPrimaryContainer = AppColor.green900,
    secondary = AppColor.green300,
    onSecondary = AppColor.white,
    secondaryContainer = AppColor.green100,
    onSecondaryContainer = AppColor.green900,
    tertiary = AppColor.teal400,
    onTertiary = AppColor.white,
    tertiaryContainer = AppColor.cyan100,
    onTertiaryContainer = AppColor.teal900,
    error = AppColor.red900,
    onError = AppColor.white,
    errorContainer = AppColor.red100,
    onErrorContainer = AppColor.red900,
    background = AppColor.gray100,
    onBackground = AppColor.gray900,
    surface = AppColor.gray100,
    onSurface = AppColor.gray900,
    surfaceVariant = AppColor.lightGreen100,
    onSurfaceVariant = AppColor.gray800,
    outline = AppColor.gray600,
    outlineVariant = AppColor.blueGray100,
    scrim = AppColor.black,
    inverseSurface = AppColor.blueGray900,
    inverseOnSurface = AppColor.blueGray50,
    inversePrimary = AppColor.green300,
    surfaceDim = AppColor.gray300,
    surfaceBright = AppColor.gray100,
    surfaceContainerLowest = AppColor.white,
    surfaceContainerLow = AppColor.brown50,
    surfaceContainer = AppColor.gray200,
    surfaceContainerHigh = AppColor.gray200,
    surfaceContainerHighest = AppColor.gray200,
)

val primaryLight = Color(0xFF39693C)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFBAF0B7)
val onPrimaryContainerLight = Color(0xFF002106)
val secondaryLight = Color(0xFF526350)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD5E8D0)
val onSecondaryContainerLight = Color(0xFF101F10)
val tertiaryLight = Color(0xFF39656B)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFBCEBF2)
val onTertiaryContainerLight = Color(0xFF001F23)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF7FBF2)
val onBackgroundLight = Color(0xFF181D18)
val surfaceLight = Color(0xFFF7FBF2)
val onSurfaceLight = Color(0xFF181D18)
val surfaceVariantLight = Color(0xFFDEE5D9)
val onSurfaceVariantLight = Color(0xFF424940)
val outlineLight = Color(0xFF72796F)
val outlineVariantLight = Color(0xFFC2C9BD)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2D322C)
val inverseOnSurfaceLight = Color(0xFFEEF2E9)
val inversePrimaryLight = Color(0xFF9ED49C)
val surfaceDimLight = Color(0xFFD7DBD3)
val surfaceBrightLight = Color(0xFFF7FBF2)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF1F5EC)
val surfaceContainerLight = Color(0xFFEBEFE6)
val surfaceContainerHighLight = Color(0xFFE6E9E1)
val surfaceContainerHighestLight = Color(0xFFE0E4DB)


//val primaryDark = Color(0xFF9ED49C)
//val onPrimaryDark = Color(0xFF053911)
//val primaryContainerDark = Color(0xFF205026)
//val onPrimaryContainerDark = Color(0xFFBAF0B7)
//val secondaryDark = Color(0xFFB9CCB4)
//val onSecondaryDark = Color(0xFF243424)
//val secondaryContainerDark = Color(0xFF3A4B39)
//val onSecondaryContainerDark = Color(0xFFD5E8D0)
//val tertiaryDark = Color(0xFFA1CED5)
//val onTertiaryDark = Color(0xFF00363C)
//val tertiaryContainerDark = Color(0xFF1F4D53)
//val onTertiaryContainerDark = Color(0xFFBCEBF2)
//val errorDark = Color(0xFFFFB4AB)
//val onErrorDark = Color(0xFF690005)
//val errorContainerDark = Color(0xFF93000A)
//val onErrorContainerDark = Color(0xFFFFDAD6)
//val backgroundDark = Color(0xFF101410)
//val onBackgroundDark = Color(0xFFE0E4DB)
//val surfaceDark = Color(0xFF101410)
//val onSurfaceDark = Color(0xFFE0E4DB)
//val surfaceVariantDark = Color(0xFF424940)
//val onSurfaceVariantDark = Color(0xFFC2C9BD)
//val outlineDark = Color(0xFF8C9388)
//val outlineVariantDark = Color(0xFF424940)
//val scrimDark = Color(0xFF000000)
//val inverseSurfaceDark = Color(0xFFE0E4DB)
//val inverseOnSurfaceDark = Color(0xFF2D322C)
//val inversePrimaryDark = Color(0xFF39693C)
//val surfaceDimDark = Color(0xFF101410)
//val surfaceBrightDark = Color(0xFF363A34)
//val surfaceContainerLowestDark = Color(0xFF0B0F0A)
//val surfaceContainerLowDark = Color(0xFF181D18)
//val surfaceContainerDark = Color(0xFF1C211B)
//val surfaceContainerHighDark = Color(0xFF272B26)
//val surfaceContainerHighestDark = Color(0xFF313630)
